package com.decrease.view.panels;

import com.decrease.EcommerceT1LpApplication;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class FinishedOrderTest extends javax.swing.JPanel {

    public FinishedOrderTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        downloadInvoiceBtn = new javax.swing.JButton();

        textLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLabel.setText("YOUR ORDER IS FINISHED!");

        backBtn.setText("Back");

        downloadInvoiceBtn.setText("Download invoice");
        downloadInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadInvoiceBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(backBtn)
                .addGap(188, 188, 188)
                .addComponent(downloadInvoiceBtn)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(downloadInvoiceBtn))
                .addGap(204, 204, 204))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Por enquanto, só vou gerar a nota fiscal e armazenar na pasta notas-fiscais no endereço ./Decrease-WorkShop-5P\notas-fiscais-testes 
    private void downloadInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadInvoiceBtnMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Invoice");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
//        fileChooser.showOpenDialog(this);

        int userSelection = fileChooser.showSaveDialog(EcommerceT1LpApplication.mainFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File selectedDirectory = fileChooser.getSelectedFile();
            String directoryChoosed = selectedDirectory.getAbsolutePath();
            EcommerceT1LpApplication.mainFrame.invoiceController.generateInvoice(directoryChoosed);
        }
    }//GEN-LAST:event_downloadInvoiceBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton downloadInvoiceBtn;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
